import asyncio
import json
import logging
import os
import textwrap
from datetime import datetime
from typing import Dict, List, Optional

import urllib.request

from dotenv import load_dotenv
from livekit.agents import (
    Agent,
    AgentServer,
    AgentSession,
    JobContext,
    TurnHandlingOptions,
    cli,
    inference,
    llm,
    room_io,
)
from livekit.plugins import ai_coustics, cartesia, groq, silero

logger = logging.getLogger("agent")

load_dotenv(".env.local")


import re
import uuid

_offline_projects_store = {}
_room_chat_memory: Dict[str, list] = {}


@llm.function_tool
async def create_build_project_plan(title: str, specification: str) -> str:
    """Draft a new build project plan and return the project ID and generated plan summary."""
    slug = re.sub(r'[^a-zA-Z0-9_-]', '_', title.lower())
    draft_workspace = os.path.abspath(f"C:\\Users\\saisr\\Projects\\SANA-LiveKit\\drafts\\{slug}")
    try:
        backend_url = os.getenv("BACKEND_URL", "http://127.0.0.1:8000")
        req_data = json.dumps({
            "title": title,
            "specification": specification,
            "workspace_path": draft_workspace,
        }).encode("utf-8")
        req = urllib.request.Request(
            f"{backend_url}/v1/build/projects",
            data=req_data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=5) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            pid = data.get("project_id")
            summary = data.get("plan_summary")
            return f"Project created successfully with ID {pid}. Workspace: {draft_workspace}. Plan Summary: {summary}"
    except Exception as e:
        logger.warning(f"Error calling create_build_project_plan backend endpoint: {e}")
        fallback_pid = f"proj-{uuid.uuid4().hex[:8]}"
        _offline_projects_store[fallback_pid] = {
            "title": title,
            "specification": specification,
            "workspace_path": draft_workspace,
        }
        return (
            f"Project plan drafted for '{title}' with ID {fallback_pid}. "
            f"Draft workspace: '{draft_workspace}'. Awaiting explicit user approval before execution."
        )


@llm.function_tool
async def approve_and_execute_build_project(project_id: str) -> str:
    """Explicitly approve and trigger execution for a drafted build project."""
    try:
        backend_url = os.getenv("BACKEND_URL", "http://127.0.0.1:8000")
        req = urllib.request.Request(
            f"{backend_url}/v1/build/projects/{project_id}/approve",
            data=b"{}",
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return f"Execution result summary: {data.get('result_summary')}"
    except Exception as e:
        logger.warning(f"Error calling approve_and_execute_build_project backend endpoint: {e}. Running local file drafting fallback.")
        offline_data = _offline_projects_store.get(project_id, {})
        workspace = offline_data.get("workspace_path") or os.path.abspath(f"C:\\Users\\saisr\\Projects\\SANA-LiveKit\\drafts\\project_{project_id}")
        spec = offline_data.get("specification") or "Scaffold project"
        title = offline_data.get("title") or "Build Target"

        os.makedirs(workspace, exist_ok=True)
        spec_path = os.path.join(workspace, "project_spec.md")
        with open(spec_path, "w", encoding="utf-8") as f:
            f.write(f"# Project Blueprint & Specification: {title}\n\n**Specification:** {spec}\n**Status:** Executed\n")
        
        main_path = os.path.join(workspace, "main.py")
        with open(main_path, "w", encoding="utf-8") as f:
            f.write(f"# Auto-generated by SaNa Build Engine\n# Project: {title}\n\ndef main():\n    print('Running {title}')\n\nif __name__ == '__main__':\n    main()\n")

        return f"Build execution completed for project {project_id}. Generated files 'project_spec.md' and 'main.py' in workspace '{workspace}'."


def get_greeting_for_mode(mode: str) -> str:
    m = mode.lower()
    if m == "debate":
        return "Ready to test your ideas? What topic shall we debate about?"
    elif m == "brainstorm":
        return "Okay, what are we brainstorming about?"
    elif m == "build":
        return "Hey, ready to build a new project? What feature shall we build today?"
    else:
        return "Hey there! What are we planning to do today?"


def get_mode_instructions(mode: str = "general") -> str:
    today_str = datetime.now().strftime("%B %d, %Y")
    normalized_mode = mode.lower()

    if normalized_mode == "debate":
        mode_header = """\
# MANDATORY ACTIVE ROLE: DEBATE SPARRING PARTNER
You are Sana, an unyielding, fierce, and highly analytical technical sparring partner. You are currently in DEBATE MODE.

YOUR MANDATORY BEHAVIOR FOR EVERY SINGLE TURN:
- YOU MUST NEVER AGREE WITH THE USER AT ANY POINT IN THIS CONVERSATION.
- NEVER SAY "THAT IS A FAIR POINT", "YOU HAVE A POINT", "GOOD POINT", OR "I AGREE". DO NOT CONCEDE GROUND.
- EVEN IF THE USER PRESENTS A STRONG ARGUMENT, IMMEDIATELY PUSH BACK WITH A COUNTER-EXAMPLE, FLAWS, HIDDEN COSTS, OR SCALABILITY RISKS.
- START EVERY RESPONSE DIRECTLY WITH A REBUTTAL OR SKEPTICAL CHALLENGE.
- Force the user to continuously defend their reasoning and choices.
- If asked what mode you are in, answer clearly: "I am in Debate Mode."
"""
    elif normalized_mode == "brainstorm":
        mode_header = """\
# MANDATORY ACTIVE ROLE: CREATIVE BRAINSTORMING PARTNER
You are Sana, an energetic, creative co-founder and ideation partner. You are currently in BRAINSTORM MODE.

YOUR MANDATORY BEHAVIOR FOR EVERY SINGLE TURN:
- ALWAYS PITCH BOLD, UNVENTURED CREATIVE IDEAS AND HELP EXPAND INCOMPLETE CONCEPTS.
- NEVER GIVE PASSIVE, GENERIC ASSISTANT REPLIES OR SIMPLE AGREEMENTS.
- FOR EVERY USER STATEMENT, OFFER 2 TO 3 INNOVATIVE FEATURE VARIATIONS OR UNCONVENTIONAL ANGLES.
- ASK AT LEAST ONE PROBING QUESTION ABOUT TARGET USERS, KEY FEATURES, TECH STACK OPTIONS, OR PRODUCT VISION.
- BRAINSTORM TO BUILD HANDOFF: When the user expresses clear intent to build (e.g., "Let's build it", "Make this a project", "I want to start building"), acknowledge their decision warmly, state a 2-sentence summary of the vision, and ask if they are ready to transition to Build Mode.
- If asked what mode you are in, answer clearly: "I am in Brainstorm Mode."
"""
    elif normalized_mode == "build":
        mode_header = """\
# MANDATORY ACTIVE ROLE: TECH LEAD & BUILD ORCHESTRATOR
You are Sana, a decisive, precise Tech Lead and Build Orchestrator. You are currently in BUILD MODE.

YOUR MANDATORY BEHAVIOR FOR EVERY SINGLE TURN:
- HELP THE USER DEFINE CLEAR PROJECT REQUIREMENTS, SPECIFICATIONS, AND ARCHITECTURE PLANS.
- EXPLICIT APPROVAL GATE: NEVER TRIGGER CODE EXECUTION OR FILE MUTATION AUTOMATICALLY. ALWAYS PRESENT THE PLAN CLEARLY AND ASK FOR THE USER'S EXPLICIT APPROVAL ("Are you ready to approve and execute this plan?").
- WHEN BUILD EXECUTION FINISHES, SUMMARIZE THE GENERATED FILES AND VERIFICATION RESULTS IN 2 TO 3 CLEAR, DIRECT SENTENCES.
- If asked what mode you are in, answer clearly: "I am in Build Mode."
"""
    else:
        mode_header = """\
# MANDATORY ACTIVE ROLE: GENERAL ASSISTANT
You are Sana, an intelligent, friendly, and reliable developer assistant. You are currently in GENERAL MODE.

YOUR MANDATORY BEHAVIOR:
- Provide clear, helpful, and direct answers to developer questions.
- Keep replies brief, friendly, and professional.
- If asked what mode you are in, answer clearly: "I am in General Mode."
"""

    grounding_and_rules = f"""\
# Temporal Grounding
- Today's date is {today_str}.
- The current President of the United States is Donald Trump (who assumed office for his second term in January 2025).

# Output rules (Voice Output)
- Respond in plain text only. Never use JSON, markdown, bullet points, numbered lists, tables, code blocks, emojis, or formatting tags.
- Keep replies brief: one to three sentences max per response. Ask one question at a time.
- Spell out numbers, phone numbers, or email addresses.
- Omit `https://` when listing URLs.

# Guardrails
- Stay within safe, lawful, and appropriate use; decline harmful requests.
- For medical, legal, or financial topics, provide general info only.
"""

    return f"{mode_header}\n{grounding_and_rules}"


class Assistant(Agent):
    def __init__(self, mode: str = "general") -> None:
        self.current_mode = mode
        super().__init__(
            llm=inference.LLM(model="google/gemma-4-31b-it"),
            instructions=get_mode_instructions(mode),
        )

    async def set_mode(self, new_mode: str) -> None:
        self.current_mode = new_mode
        new_inst = get_mode_instructions(new_mode)
        self._instructions = new_inst
        await self.update_instructions(new_inst)
        logger.info(f"Updated Assistant instructions for mode: {new_mode}")


server = AgentServer()


@server.rtc_session(agent_name="voice_agent")
async def my_agent(ctx: JobContext):
    groq_key = os.getenv("GROQ_API_KEY")
    cartesia_key = os.getenv("CARTESIA_API_KEY")
    logger.info(f"Connecting session in room '{ctx.room.name}'. GROQ_API_KEY present: {bool(groq_key)}, CARTESIA_API_KEY present: {bool(cartesia_key)}")

    assistant = Assistant(mode="general")
    greeting_spoken = False

    session = AgentSession(
        stt=groq.STT(model="whisper-large-v3-turbo", api_key=groq_key),
        llm=groq.LLM(model="llama-3.3-70b-versatile", api_key=groq_key),
        tts=cartesia.TTS(api_key=cartesia_key),
        vad=silero.VAD.load(),
        tools=[create_build_project_plan, approve_and_execute_build_project],
        preemptive_generation=False,
    )

    await session.start(
        agent=assistant,
        room=ctx.room,
    )

    current_applied_mode = None

    async def apply_mode(new_mode: str):
        nonlocal current_applied_mode
        if current_applied_mode == new_mode:
            return
        current_applied_mode = new_mode
        logger.info(f"Applying mode switch: '{new_mode}'")
        await assistant.set_mode(new_mode)

        # Update system message IN PLACE at index 0 of session.history
        new_instructions = get_mode_instructions(new_mode)
        if hasattr(session, "history") and session.history:
            try:
                system_found = False
                for msg in session.history.messages():
                    if getattr(msg, "role", None) == "system":
                        msg.content = [new_instructions]
                        system_found = True
                        logger.info(f"Updated in-place system message at index 0 for mode: '{new_mode}'")
                        break
                if not system_found:
                    session.history.add_message(
                        role="system",
                        content=new_instructions,
                    )
            except Exception as e:
                logger.warning(f"Failed to update session.history system prompt: {e}")

    async def speak_greeting(mode: str):
        nonlocal greeting_spoken
        if greeting_spoken:
            return
        greeting_spoken = True
        await asyncio.sleep(0.4)
        greeting = get_greeting_for_mode(mode)
        logger.info(f"Speaking initial mode greeting for mode '{mode}': '{greeting}'")
        try:
            await session.say(greeting)
        except Exception as e:
            logger.warning(f"Failed to speak initial mode greeting: {e}", exc_info=True)

    @ctx.room.on("data_received")
    def on_data_received(data_packet):
        try:
            payload = json.loads(data_packet.data.decode("utf-8"))
            if payload.get("type") == "mode_switch":
                new_mode = payload.get("mode", "general")
                is_initial = payload.get("is_initial", False)
                if current_applied_mode == new_mode:
                    return
                logger.info(f"Received mode switch payload: {new_mode} (is_initial: {is_initial})")
                asyncio.create_task(apply_mode(new_mode))

                if is_initial:
                    asyncio.create_task(speak_greeting(new_mode))
        except Exception as e:
            logger.warning(f"Error parsing data packet in voice agent: {e}")

    @ctx.room.on("participant_metadata_changed")
    def on_metadata_changed(participant, old_metadata, new_metadata):
        logger.info(f"Participant metadata changed: {new_metadata}")
        if new_metadata:
            try:
                meta = json.loads(new_metadata)
                mode = meta.get("mode", "general")
                asyncio.create_task(apply_mode(mode))
            except Exception as e:
                logger.warning(f"Error parsing updated metadata: {e}")

    @ctx.room.on("participant_connected")
    def on_participant_connected(participant):
        logger.info(f"Participant connected: {participant.identity}")
        mode = "general"
        if participant.metadata:
            try:
                meta = json.loads(participant.metadata)
                mode = meta.get("mode", mode)
            except Exception:
                pass
        asyncio.create_task(apply_mode(mode))
        asyncio.create_task(speak_greeting(mode))

    # Fallback greeting if participant is already connected upon agent join
    for p in ctx.room.remote_participants.values():
        mode = "general"
        if p.metadata:
            try:
                meta = json.loads(p.metadata)
                mode = meta.get("mode", mode)
            except Exception:
                pass
        asyncio.create_task(apply_mode(mode))
        asyncio.create_task(speak_greeting(mode))


if __name__ == "__main__":
    cli.run_app(server)
