# Auto-generated by SaNa DeepCode Execution Engine
# Prompt: A command line calculator written in Python. It will support basic arithmetic operations like addition, subtraction, multiplication, and division through a simple user interface in the terminal. The project will consist of a main.py file.

def main():
    print('Executing SaNa build target for prompt: A command line calculator written in Python. It will support basic arithmetic operations like addition, subtraction, multiplication, and division through a simple user interface in the terminal. The project will consist of a main.py file.')

if __name__ == '__main__':
    main()
