# Auto-generated by SaNa DeepCode Execution Engine
# Prompt: A simple, single-page web calculator. It will use HTML for the structure, CSS for a clean and centered layout, and vanilla JavaScript to handle basic arithmetic operations including addition, subtraction, multiplication, and division. The design will be responsive and suitable for a demo.

def main():
    print('Executing SaNa build target for prompt: A simple, single-page web calculator. It will use HTML for the structure, CSS for a clean and centered layout, and vanilla JavaScript to handle basic arithmetic operations including addition, subtraction, multiplication, and division. The design will be responsive and suitable for a demo.')

if __name__ == '__main__':
    main()
