import asyncio
import logging
import uuid
from typing import AsyncGenerator, Dict, Optional
from datetime import datetime

from app.models.deepcode_models import (
    DeepCodeEvent,
    DeepCodeSession,
    DeepCodeStep,
)

logger = logging.getLogger("backend.deepcode_adapter")


class DeepCodeAdapter:
    """
    Adapter abstraction insulating SaNa backend from DeepCode agentic build engine CLI/JSON details.
    """

    def __init__(self):
        self._sessions: Dict[str, DeepCodeSession] = {}

    def create_session(
        self,
        workspace_path: str,
        model: str = "google/gemma-4-31b-it",
        connection_id: Optional[str] = None,
        access_level: str = "full-access",
        session_id: Optional[str] = None,
    ) -> DeepCodeSession:
        resolved_session_id = session_id or f"dc-sess-{uuid.uuid4().hex[:8]}"
        existing = self._sessions.get(resolved_session_id)
        if existing:
            existing.workspace_path = workspace_path
            existing.model = model
            existing.connection_id = connection_id
            existing.access_level = access_level
            existing.updated_at = datetime.utcnow().isoformat()
            return existing

        session = DeepCodeSession(
            session_id=resolved_session_id,
            workspace_path=workspace_path,
            model=model,
            connection_id=connection_id,
            access_level=access_level,
            status="idle",
        )
        self._sessions[resolved_session_id] = session
        logger.info("Created DeepCode session %s for workspace %s", resolved_session_id, workspace_path)
        return session

    def get_session(self, session_id: str) -> Optional[DeepCodeSession]:
        return self._sessions.get(session_id)

    def ensure_session(
        self,
        session_id: str,
        workspace_path: str,
        model: str = "google/gemma-4-31b-it",
        connection_id: Optional[str] = None,
        access_level: str = "full-access",
    ) -> DeepCodeSession:
        return self.create_session(
            workspace_path=workspace_path,
            model=model,
            connection_id=connection_id,
            access_level=access_level,
            session_id=session_id,
        )

    async def run_turn(
        self,
        session_id: str,
        prompt: str,
    ) -> AsyncGenerator[DeepCodeEvent, None]:
        session = self._sessions.get(session_id)
        if not session:
            raise ValueError(f"Session {session_id} not found")

        session.status = "running"
        session.updated_at = datetime.utcnow().isoformat()

        yield DeepCodeEvent(
            event_type="step_start",
            message=f"Starting DeepCode turn for session {session_id}",
            details={"prompt": prompt, "workspace": session.workspace_path},
        )
        await asyncio.sleep(0.1)

        import os
        import re

        workspace = os.path.abspath(os.path.normpath(session.workspace_path))
        session.workspace_path = workspace
        os.makedirs(workspace, exist_ok=True)

        def write_file_safely(file_path: str, content: str) -> None:
            parent_dir = os.path.dirname(file_path)
            if parent_dir:
                os.makedirs(parent_dir, exist_ok=True)
            with open(file_path, "w", encoding="utf-8") as file_handle:
                file_handle.write(content)

        workspace_name = os.path.basename(workspace) or "generated_project"
        package_name = re.sub(r"[^a-zA-Z0-9_]", "_", workspace_name.lower()).strip("_") or "generated_project"
        if package_name[0].isdigit():
            package_name = f"project_{package_name}"

        files_to_write = {
            "project_spec.md": (
                f"# Project Blueprint & Specification\n\n"
                f"**Prompt:** {prompt}\n"
                "**Generated By:** SaNa Build Mode Agent\n"
                "**Status:** Active\n\n"
                "## Specification Details\n"
                f"- Target Workspace: `{workspace}`\n"
                f"- Python Package: `{package_name}`\n"
                "- Architecture: Layered Python scaffold with CLI entrypoint, src package, and tests\n"
            ),
            "README.md": (
                f"# {workspace_name.replace('_', ' ').title()}\n\n"
                "This project scaffold was generated by SaNa Build Mode.\n\n"
                "## Original request\n"
                f"{prompt}\n\n"
                "## Generated structure\n"
                "- `main.py` root entrypoint\n"
                f"- `src/{package_name}/` package scaffold\n"
                "- `tests/` starter test\n"
                "- `project_spec.md` captured specification\n"
            ),
            ".gitignore": "__pycache__/\n*.pyc\n.pytest_cache/\n.venv/\n.env\n",
            "pyproject.toml": (
                "[project]\n"
                f'name = "{package_name.replace("_", "-")}"\n'
                'version = "0.1.0"\n'
                'description = "Generated by SaNa Build Mode"\n'
                'requires-python = ">=3.11"\n\n'
                "[tool.pytest.ini_options]\n"
                'testpaths = ["tests"]\n'
            ),
            "main.py": (
                f"from src.{package_name}.app import main\n\n"
                "if __name__ == '__main__':\n"
                "    main()\n"
            ),
            os.path.join("src", package_name, "__init__.py"): '"""Generated application package."""\n',
            os.path.join("src", package_name, "app.py"): (
                f"PROMPT = {prompt!r}\n\n"
                "def build_summary() -> str:\n"
                '    return f"SaNa generated scaffold for: {PROMPT}"\n\n'
                "def main() -> None:\n"
                "    print(build_summary())\n"
            ),
            os.path.join("tests", "test_app.py"): (
                f"from src.{package_name}.app import build_summary\n\n"
                "def test_build_summary_mentions_generated_scaffold():\n"
                "    summary = build_summary()\n"
                '    assert "SaNa generated scaffold" in summary\n'
            ),
        }

        for relative_path, content in files_to_write.items():
            write_file_safely(os.path.join(workspace, relative_path), content)

        spec_file_path = os.path.join(workspace, "project_spec.md")
        step1 = DeepCodeStep(
            step_index=1,
            action="analyze_requirements",
            status="completed",
            description=f"Analyzed prompt: '{prompt}'",
            output=f"Created specification at '{spec_file_path}'",
        )
        session.steps.append(step1)
        yield DeepCodeEvent(
            event_type="file_edit",
            message=f"Created specification file '{spec_file_path}'",
            details={"step": step1.model_dump(), "file_path": spec_file_path},
        )
        await asyncio.sleep(0.1)

        main_file_path = os.path.join(workspace, "main.py")
        step2 = DeepCodeStep(
            step_index=2,
            action="scaffold_project",
            status="completed",
            description=f"Scaffolded multi-file project rooted at '{main_file_path}'",
            output="Generated README, package metadata, src package, starter tests, and root entrypoint.",
        )
        session.steps.append(step2)
        yield DeepCodeEvent(
            event_type="step_complete",
            message=f"Scaffolded multi-file project with entrypoint '{main_file_path}'",
            details={
                "step": step2.model_dump(),
                "file_path": main_file_path,
                "generated_files": sorted(files_to_write.keys()),
            },
        )

        session.status = "completed"
        session.updated_at = datetime.utcnow().isoformat()

    def resume_session(self, session_id: str) -> DeepCodeSession:
        session = self._sessions.get(session_id)
        if not session:
            raise ValueError(f"Session {session_id} not found")
        session.status = "idle"
        session.updated_at = datetime.utcnow().isoformat()
        logger.info("Resumed DeepCode session %s", session_id)
        return session
